server:
  port: 9527

spring:
  application:
    name: ruoyi-gateway
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  profiles:
    active: dev
  cache:
    ehcache:
      config: classpath:ehcache.xml
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: ruoyi-config
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        # 认证中心
        - id: ruoyi-auth
          uri: lb://ruoyi-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - StripPrefix=1
        # 代码生成
        - id: ruoyi-gen
          uri: lb://ruoyi-gen
          predicates:
            - Path=/gen/**
          filters:
            - StripPrefix=1
        # dfs
        - id: ruoyi-dfs
          uri: lb://ruoyi-dfs
          predicates:
            - Path=/dfs/**
          filters:
            - StripPrefix=1
        #system 模块
        - id: ruoyi-system
          uri: lb://ruoyi-system
          predicates:
            - Path=/system/**
          filters:
            # 限流配置
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 2000
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        #es 模块
        - id: gateway_es
          uri: http://localhost:8005/
          predicates:
            - Path=/es/**
          filters:
            # 限流配置
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1000
                redis-rate-limiter.burstCapacity: 2000
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
        #gateway_basic 模块
        - id: gateway_basic
          uri: http://192.168.100.5:1521/
          predicates:
            - Path=/basic/**
          filters:
            # 限流配置
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@remoteAddrKeyResolver}'
                redis-rate-limiter.replenishRate: 1000  #允许用户每秒处理多少个请求
                redis-rate-limiter.burstCapacity: 2000  #令牌桶的容量，允许在一秒钟内完成的最大请求数
              # 降级配置
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: 'forward:/fallback'
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址      

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'